Next Gen GitHub Tag Action
anothrNick/github-tag-action pull request #252
Opened 2023-04-03 12:50 UTC by beholdenkey

# Summary of changes

This is a first iteration refactor. A lot of the code has been modified and updated. However, there is still a lot of room for improvement. I have a dev branch where I am testing out switching from the node server to using Python for the GitPython and SemVer Libraries. That will offer a greater level of performance and extensibility.

## Breaking Changes

There are not necessarily breaking changes. The functionality of the action has stayed the same; however,r a lot of the code supporting it has.

(**YES** / NO)

## How changes have been tested

- Local Unit Tests, Testing the container build/workflows; this will be the first iteration of the pull request to the master origin.

## List any unknowns

- Lots of changes/lots of unknowns. This will more than likely require iterations to complete changes and successfully merge.

2023-04-04 13:54 UTC, matthiasgubler commented on action.yml
> +    required: false
Question: why are you adding these two values as inputs when env-vars provide everything else? Keeping this way would mean, to adjust the examples to something like:
```
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.61.0 # Don't use @master unless you're happy to test the latest version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
       with:
          DEFAULT_BUMP: "patch"
```

As the inputs need to be provided in a different matter. Also accessing the values would need to change to:
```
${{ inputs.DEFAULT_BUMP }}
```

Last but not least, they should be renamed to kebab-case `default-bump`.

I would delete lines 5 - 12 in this case

2023-04-07 21:48 UTC, sbe-arg reviewed
Thank you for this. On the phone it looks a considerable improvement in practice.


I have 0 time to check this pr this week but maybe @sammcj can have a look and test it.

2023-04-07 22:41 UTC, sammcj requested changes
Awesome effort! Really appreciate the contributions.

One thing I'd say especially given this is a big PR - it should really include some basic tests.

It doesn't have to be some big fancy testing framework but at least a script or functions that validate several scenarios that this may be used for.

2023-04-07 22:41 UTC, sammcj commented on .github/workflows/publish.yml
> +      - name: Install cosign
Oh nice! Great to see some security improvements!

2023-04-07 22:41 UTC, sammcj commented on .github/workflows/scripts/tag_check.sh
> +#!/bin/bash
`!/usr/bin/env bash`

Just so it's portable.

2023-04-07 22:41 UTC, sammcj commented on .github/workflows/scripts/tag_check.sh
> +set -euo pipefail
A nice little addition I like to add to shell scripts to add set -x only if you're debugging:

```bash
DEBUG=${DEBUG:-false}

function debug() {
  echo "Debug mode enabled" >>"$GITHUB_STEP_SUMMARY"

  # Print all environment variables
  env | sort >>"$GITHUB_STEP_SUMMARY"
  echo -e "\n" >>"$GITHUB_STEP_SUMMARY"

	set -x
}

if [[ $DEBUG == 'true' ]]; then
  debug
fi
```

2023-04-07 22:41 UTC, sammcj commented on .github/workflows/scripts/tag_check.sh
> +echo "PRE Part: $PRE_OUTPUT_PART" >>"$GITHUB_STEP_SUMMARY"
A little trick with this to make it render in a nice table can be something like this:

```bash
OUTPUT_SUMMARY="\n
| Output       | Value                 | \n
| ------------ | --------------------- | \n
|              |                       | \n
| MAIN Tag     | ${MAIN_OUTPUT_TAG}    | \n
| MAIN New tag | ${MAIN_OUTPUT_NEWTAG} | \n
| MAIN Part    | ${MAIN_OUTPUT_PART}   | \n
| PRE Tag      | ${PRE_OUTPUT_TAG}     | \n
| PRE New tag  | ${PRE_OUTPUT_NEWTAG}  | \n
| PRE Part     | ${PRE_OUTPUT_PART}    | \n
"

echo -e "$OUTPUT_SUMMARY" >>"$GITHUB_STEP_SUMMARY"

2023-04-07 22:41 UTC, sammcj commented on CODE_OF_CONDUCT.md
> +Examples of unacceptable behavior include:
Behaviour is the correct international spelling.

Behavior is specific to American.

2023-04-07 22:41 UTC, sammcj commented on .github/workflows/scripts/tag_check.sh
> +	if [[ $MAIN_OUTPUT_TAG == "$MAIN_OUTPUT_NEWTAG" ]]; then
I think the variable on the left of the comparison should be quoted as well.

2023-04-07 22:41 UTC, sammcj commented on .github/workflows/scripts/tag_check.sh
> +pre="$(verlt "$PRE_OUTPUT_TAG" "$PRE_OUTPUT_NEWTAG" && true || false)"
It feels weird to have double quotes inside a double quoted string but it does seem to work on my machine as well 🤷

2023-05-08 12:44 UTC, sbe-arg requested changes

2023-05-08 12:44 UTC, sbe-arg commented on entrypoint.sh
> -setOutput "tag" "$new" # this needs to go in v2 is breaking change
I would like this comment to remain specially since broke the flows for a LOT lots of people

2023-05-26 00:01 UTC, closed without merging

2023-05-26 00:49 UTC, sbe-arg commented
:(